services:
  mysql:
    image: mysql:8.0
    container_name: hoop-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - hoop_mysql_data:/var/lib/mysql

volumes:
  hoop_mysql_data:
